[2022-10-23T21:22:23.813+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_categorias manual__2022-10-23T21:13:29.385498+00:00 [queued]>
[2022-10-23T21:22:23.839+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_categorias manual__2022-10-23T21:13:29.385498+00:00 [queued]>
[2022-10-23T21:22:23.839+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T21:22:23.840+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 5
[2022-10-23T21:22:23.840+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T21:22:23.864+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_categorias> on 2022-10-23 21:13:29.385498+00:00
[2022-10-23T21:22:23.870+0000] {standard_task_runner.py:54} INFO - Started process 1186 to run task
[2022-10-23T21:22:23.875+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'get_categorias', 'manual__2022-10-23T21:13:29.385498+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmp2hp_qhdh']
[2022-10-23T21:22:23.877+0000] {standard_task_runner.py:83} INFO - Job 164: Subtask get_categorias
[2022-10-23T21:22:23.879+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-23T21:22:25.109+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.get_categorias manual__2022-10-23T21:13:29.385498+00:00 [running]> on host 83cd0ab98720
[2022-10-23T21:22:25.241+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=get_categorias
AIRFLOW_CTX_EXECUTION_DATE=2022-10-23T21:13:29.385498+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-23T21:13:29.385498+00:00
[2022-10-23T21:22:25.293+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sales_dw.py", line 41, in get_categorias
    categorias = pq.read_pandas("https://github.com/pedromenegat/JrDataEngineerTest/blob/main/files/categoria.parquet?raw=true").to_pandas()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1986, in read_pandas
    source, columns=columns, use_pandas_metadata=True, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1915, in read_table
    coerce_int96_timestamp_unit=coerce_int96_timestamp_unit
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1729, in __init__
    ignore_prefixes=ignore_prefixes)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 680, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 425, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 401, in _ensure_single_source
    raise FileNotFoundError(path)
FileNotFoundError: https://github.com/pedromenegat/JrDataEngineerTest/blob/main/files/categoria.parquet?raw=true
[2022-10-23T21:22:25.312+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=sales_datawarehouse, task_id=get_categorias, execution_date=20221023T211329, start_date=20221023T212223, end_date=20221023T212225
[2022-10-23T21:22:25.327+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 164 for task get_categorias (https://github.com/pedromenegat/JrDataEngineerTest/blob/main/files/categoria.parquet?raw=true; 1186)
[2022-10-23T21:22:25.374+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-23T21:22:25.433+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
