[2022-10-23T17:47:30.191+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T17:16:24.670127+00:00 [queued]>
[2022-10-23T17:47:30.208+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T17:16:24.670127+00:00 [queued]>
[2022-10-23T17:47:30.209+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T17:47:30.210+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 6
[2022-10-23T17:47:30.210+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T17:47:30.231+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_vendas> on 2022-10-23 17:16:24.670127+00:00
[2022-10-23T17:47:30.242+0000] {standard_task_runner.py:54} INFO - Started process 5921 to run task
[2022-10-23T17:47:30.250+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'get_vendas', 'manual__2022-10-23T17:16:24.670127+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmps8ie8jj4']
[2022-10-23T17:47:30.252+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask get_vendas
[2022-10-23T17:47:30.254+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-23T17:47:32.169+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T17:16:24.670127+00:00 [running]> on host 499050b57294
[2022-10-23T17:47:32.268+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=get_vendas
AIRFLOW_CTX_EXECUTION_DATE=2022-10-23T17:16:24.670127+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-23T17:16:24.670127+00:00
[2022-10-23T17:47:32.287+0000] {base.py:71} INFO - Using connection ID 'banco_vendas' for task execution.
[2022-10-23T17:47:34.285+0000] {xcom.py:600} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-10-23T17:47:34.286+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sales_dw.py", line 22, in get_vendas
    ti.xcom_push(key='ids_funcionarios', value=ids_funcionarios)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2385, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 212, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
[2022-10-23T17:47:34.314+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=sales_datawarehouse, task_id=get_vendas, execution_date=20221023T171624, start_date=20221023T174730, end_date=20221023T174734
[2022-10-23T17:47:34.342+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 55 for task get_vendas (Object of type ndarray is not JSON serializable; 5921)
[2022-10-23T17:47:34.397+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-23T17:47:34.464+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
