[2022-10-23T17:19:36.148+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.create_tables manual__2022-10-23T17:19:35.121803+00:00 [queued]>
[2022-10-23T17:19:36.160+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.create_tables manual__2022-10-23T17:19:35.121803+00:00 [queued]>
[2022-10-23T17:19:36.160+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T17:19:36.162+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-23T17:19:36.162+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T17:19:36.184+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_tables> on 2022-10-23 17:19:35.121803+00:00
[2022-10-23T17:19:36.188+0000] {standard_task_runner.py:54} INFO - Started process 4251 to run task
[2022-10-23T17:19:36.192+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'create_tables', 'manual__2022-10-23T17:19:35.121803+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmp0yap2wyg']
[2022-10-23T17:19:36.193+0000] {standard_task_runner.py:83} INFO - Job 50: Subtask create_tables
[2022-10-23T17:19:36.194+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-23T17:19:36.713+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.create_tables manual__2022-10-23T17:19:35.121803+00:00 [running]> on host 499050b57294
[2022-10-23T17:19:36.790+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=create_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-10-23T17:19:35.121803+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-23T17:19:35.121803+00:00
[2022-10-23T17:19:36.799+0000] {base.py:71} INFO - Using connection ID '***_localhost' for task execution.
[2022-10-23T17:19:36.864+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS funcionarios(		
            id_funcionario INTEGER PRIMARY KEY NOT NULL,
            nome_funcionario VARCHAR(30) NOT NULL
	    );
        CREATE TABLE IF NOT EXISTS categorias(		
            id_categoria INTEGER PRIMARY KEY NOT NULL,
            nome_categoria VARCHAR(30) NOT NULL
		);
        CREATE TABLE IF NOT EXISTS vendas(
            id_venda INTEGER PRIMARY KEY NOT NULL,
            id_funcionario INTEGER NOT NULL,
            id_categoria INTEGER NOT NULL,
            data_venda DATE NOT NULL,
            venda NUMERIC(20,5) NOT NULL,
            FOREIGN KEY (id_funcionario) 
                REFERENCES funcionarios (id_funcionario)
                ON UPDATE CASCADE ON DELETE CASCADE,
            FOREIGN KEY (id_categoria) 
                REFERENCES categorias (id_categoria)
                ON UPDATE CASCADE ON DELETE CASCADE
		);
        , parameters: None
[2022-10-23T17:19:36.880+0000] {postgres.py:96} INFO - NOTICE:  relation "funcionarios" already exists, skipping

[2022-10-23T17:19:36.881+0000] {postgres.py:96} INFO - NOTICE:  relation "categorias" already exists, skipping

[2022-10-23T17:19:36.881+0000] {postgres.py:96} INFO - NOTICE:  relation "vendas" already exists, skipping

[2022-10-23T17:19:36.896+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=sales_datawarehouse, task_id=create_tables, execution_date=20221023T171935, start_date=20221023T171936, end_date=20221023T171936
[2022-10-23T17:19:36.927+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-23T17:19:37.053+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
