[2022-10-26T00:39:14.967+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.create_tables manual__2022-10-26T00:39:12.695496+00:00 [queued]>
[2022-10-26T00:39:15.021+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.create_tables manual__2022-10-26T00:39:12.695496+00:00 [queued]>
[2022-10-26T00:39:15.022+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-26T00:39:15.023+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-26T00:39:15.024+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-26T00:39:15.056+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_tables> on 2022-10-26 00:39:12.695496+00:00
[2022-10-26T00:39:15.068+0000] {standard_task_runner.py:54} INFO - Started process 3680 to run task
[2022-10-26T00:39:15.074+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'create_tables', 'manual__2022-10-26T00:39:12.695496+00:00', '--job-id', '609', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmpo5ivodfe']
[2022-10-26T00:39:15.077+0000] {standard_task_runner.py:83} INFO - Job 609: Subtask create_tables
[2022-10-26T00:39:15.078+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-26T00:39:17.646+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.create_tables manual__2022-10-26T00:39:12.695496+00:00 [running]> on host 83cd0ab98720
[2022-10-26T00:39:17.908+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=create_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T00:39:12.695496+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-26T00:39:12.695496+00:00
[2022-10-26T00:39:17.924+0000] {base.py:71} INFO - Using connection ID '***_localhost' for task execution.
[2022-10-26T00:39:18.094+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS dimFuncionarios(		
            id_funcionario INTEGER PRIMARY KEY NOT NULL,
            nome_funcionario VARCHAR(30) NOT NULL
	    );
        CREATE TABLE IF NOT EXISTS dimCategorias(		
            id INTEGER PRIMARY KEY NOT NULL,
            nome_categoria VARCHAR(30) NOT NULL
		);		
		CREATE TABLE IF NOT EXISTS fatoVendas(
            id_venda INTEGER PRIMARY KEY NOT NULL,
            id_funcionario INTEGER NOT NULL,
            id_categoria INTEGER NOT NULL,
            data_venda DATE NOT NULL,
            venda NUMERIC(20,5) NOT NULL,
            FOREIGN KEY (id_funcionario) 
                REFERENCES dimFuncionarios (id_funcionario)
                ON UPDATE CASCADE ON DELETE CASCADE,
            FOREIGN KEY (id_categoria) 
                REFERENCES dimCategorias (id)
                ON UPDATE CASCADE ON DELETE CASCADE
		);
        , parameters: None
[2022-10-26T00:39:18.106+0000] {postgres.py:96} INFO - NOTICE:  relation "dimfuncionarios" already exists, skipping

[2022-10-26T00:39:18.107+0000] {postgres.py:96} INFO - NOTICE:  relation "dimcategorias" already exists, skipping

[2022-10-26T00:39:18.108+0000] {postgres.py:96} INFO - NOTICE:  relation "fatovendas" already exists, skipping

[2022-10-26T00:39:18.132+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=sales_datawarehouse, task_id=create_tables, execution_date=20221026T003912, start_date=20221026T003914, end_date=20221026T003918
[2022-10-26T00:39:18.213+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-26T00:39:18.468+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
