[2022-10-24T16:41:50.968+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-24T16:41:40.584519+00:00 [queued]>
[2022-10-24T16:41:51.023+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-24T16:41:40.584519+00:00 [queued]>
[2022-10-24T16:41:51.035+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-24T16:41:51.037+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-24T16:41:51.037+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-24T16:41:51.122+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_funcionarios> on 2022-10-24 16:41:40.584519+00:00
[2022-10-24T16:41:51.148+0000] {standard_task_runner.py:54} INFO - Started process 4637 to run task
[2022-10-24T16:41:51.164+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'get_funcionarios', 'manual__2022-10-24T16:41:40.584519+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmpze5cridh']
[2022-10-24T16:41:51.169+0000] {standard_task_runner.py:83} INFO - Job 221: Subtask get_funcionarios
[2022-10-24T16:41:51.171+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-24T16:42:07.010+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-24T16:41:40.584519+00:00 [running]> on host 83cd0ab98720
[2022-10-24T16:42:07.836+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=get_funcionarios
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T16:41:40.584519+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-24T16:41:40.584519+00:00
[2022-10-24T16:42:07.915+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sales_dw.py", line 26, in get_funcionarios
    ids_funcionarios = json.loads(ti.xcom_pull(task_ids="get_vendas", key="ids_funcionarios"))
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-10-24T16:42:08.044+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=sales_datawarehouse, task_id=get_funcionarios, execution_date=20221024T164140, start_date=20221024T164150, end_date=20221024T164208
[2022-10-24T16:42:08.180+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 221 for task get_funcionarios (the JSON object must be str, bytes or bytearray, not NoneType; 4637)
[2022-10-24T16:42:08.276+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-24T16:42:08.479+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
